sudo : required
services:
 - docker 
 
 before_install:
  - docker build -t tuhinsarkar/docker-react -f Dockerfile.dev .
  
 script:
  - docker run -e CI=true tuhinsarkar/docker-react npm run test -- -- coverage
